export const PUBLIC_ENDPOINTS = [
  'auth/email/login',
  'auth/email/signup',
  'auth/kakao/callback',
  'auth/naver/callback',
  'auth/email/send-code',
  'auth/phone/send-code',
  'auth/email/verify',
  'auth/phone/verify',
  'auth/refresh',
  'auth/recover-account',
  'auth/find-email/send',
  'auth/find-email/verify',
  'auth/reset-password/send',
  'auth/reset-password/verify',
  'auth/reset-password',
] as const
