name: Sync Fork with Upstream

on:
  schedule:
    - cron: '0 0 * * *' # 매일 자정(UTC 기준) 자동 실행
  workflow_dispatch # 필요하면 수동 실행도 가능

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "sysysysyb"
          git config --global user.email "baeksy6067@gmail.com"

      - name: Add upstream repository
        run: git remote add upstream https://github.com/OZ-Coding-School/oz_externship_fe_02_team4

      - name: Fetch upstream changes
        run: git fetch upstream
      
      - name: Merge upstream changes into main
        run: |
          git checkout main
          git merge upstream/main --allow-unrelated-histories || true

      - name: Push changes to forked repository
        run: git push origin main